services: 
  api: 
    image: golang:1.24.1
    working_dir: /usr/src/app
    volumes: 
      - .:/usr/src/app
    ports: 
      - "8080:8080"
    environment:
      - OWNER_PASSWORD=123456
      - DSN=host=db user=user password=password dbname=bank_idk port=5432 sslmode=disable 
      - PORT=:8080
      - JWT_SECRET=RICE
    command: 
      go run main.go
    depends_on:
      - db

  db:
    image: postgres:latest 
    ports: 
      - "15432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_idk
    volumes:
      - pgdata2:/var/lib/postgresql/data

volumes:
  pgdata2:
